version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- ps: ./scripts/build.ps1
environment:
  APPVEYOR_REPO_TAG: true
artifacts:
- path: MyCashFlowSharp/MyCashFlowSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: MyCashFlowSharp/MyCashFlowSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  api_key:
    secure: 1rl2+q7wHn/ndf8DoJ0W6PuyeLEfoFBPN+aY9u37lbiPATz8vxxZcy48tiyPKjNH
  on:
    branch: master
